/*
 * SPDX-License-Identifier: MIT
 * Copyright (c) 2025 Tetsuo AI
 * https://x.com/tetsuoai
 */

/**
 * @file SocketHTTPClient-config.h
 * @brief Configuration constants for HTTP client with compile-time override.
 * @ingroup http_client
 *
 * Centralized configuration for HTTP client module.
 * All constants can be overridden at compile time with -D flags
 * or at runtime via SocketHTTPClient_Config fields.
 *
 * @see SocketHTTPClient_config_defaults() for runtime defaults.
 * @see SocketHTTPClient_Config for full structure.
 */

#ifndef SOCKETHTTPCLIENT_CONFIG_INCLUDED
#define SOCKETHTTPCLIENT_CONFIG_INCLUDED

#ifndef HTTPCLIENT_ERROR_BUFSIZE
#define HTTPCLIENT_ERROR_BUFSIZE 256
#endif

#ifndef HTTPCLIENT_POOL_HASH_SIZE
#define HTTPCLIENT_POOL_HASH_SIZE 127
#endif

#ifndef HTTPCLIENT_POOL_LARGE_HASH_SIZE
#define HTTPCLIENT_POOL_LARGE_HASH_SIZE 251
#endif

#ifndef HTTPCLIENT_POOL_LARGE_THRESHOLD
#define HTTPCLIENT_POOL_LARGE_THRESHOLD 100
#endif

#ifndef HTTPCLIENT_IO_BUFFER_SIZE
#define HTTPCLIENT_IO_BUFFER_SIZE 8192
#endif

#ifndef HTTPCLIENT_DEFAULT_CONNECT_TIMEOUT_MS
#define HTTPCLIENT_DEFAULT_CONNECT_TIMEOUT_MS 30000
#endif

#ifndef HTTPCLIENT_DEFAULT_REQUEST_TIMEOUT_MS
#define HTTPCLIENT_DEFAULT_REQUEST_TIMEOUT_MS 60000
#endif

#ifndef HTTPCLIENT_DEFAULT_DNS_TIMEOUT_MS
#define HTTPCLIENT_DEFAULT_DNS_TIMEOUT_MS 10000
#endif

#ifndef HTTPCLIENT_DEFAULT_IDLE_TIMEOUT_MS
#define HTTPCLIENT_DEFAULT_IDLE_TIMEOUT_MS 60000
#endif

#ifndef HTTPCLIENT_DEFAULT_MAX_REDIRECTS
#define HTTPCLIENT_DEFAULT_MAX_REDIRECTS 10
#endif

#ifndef HTTPCLIENT_DEFAULT_MAX_CONNS_PER_HOST
#define HTTPCLIENT_DEFAULT_MAX_CONNS_PER_HOST 6
#endif

#ifndef HTTPCLIENT_DEFAULT_MAX_TOTAL_CONNS
#define HTTPCLIENT_DEFAULT_MAX_TOTAL_CONNS 100
#endif

#ifndef HTTPCLIENT_MAX_AUTH_RETRIES
#define HTTPCLIENT_MAX_AUTH_RETRIES 2
#endif

#ifndef HTTPCLIENT_DEFAULT_ENABLE_RETRY
#define HTTPCLIENT_DEFAULT_ENABLE_RETRY 0
#endif

#ifndef HTTPCLIENT_DEFAULT_MAX_RETRIES
#define HTTPCLIENT_DEFAULT_MAX_RETRIES 3
#endif

#ifndef HTTPCLIENT_DEFAULT_RETRY_INITIAL_DELAY_MS
#define HTTPCLIENT_DEFAULT_RETRY_INITIAL_DELAY_MS 100
#endif

#ifndef HTTPCLIENT_DEFAULT_RETRY_MAX_DELAY_MS
#define HTTPCLIENT_DEFAULT_RETRY_MAX_DELAY_MS 10000
#endif

#ifndef HTTPCLIENT_DEFAULT_RETRY_ON_CONNECT
#define HTTPCLIENT_DEFAULT_RETRY_ON_CONNECT 1
#endif

#ifndef HTTPCLIENT_DEFAULT_RETRY_ON_TIMEOUT
#define HTTPCLIENT_DEFAULT_RETRY_ON_TIMEOUT 1
#endif

/* Only enable for idempotent requests (GET, HEAD, PUT, DELETE) */
#ifndef HTTPCLIENT_DEFAULT_RETRY_ON_5XX
#define HTTPCLIENT_DEFAULT_RETRY_ON_5XX 0
#endif

#ifndef HTTPCLIENT_RETRY_MULTIPLIER
#define HTTPCLIENT_RETRY_MULTIPLIER 2.0
#endif

#ifndef HTTPCLIENT_RETRY_JITTER_FACTOR
#define HTTPCLIENT_RETRY_JITTER_FACTOR 0.25
#endif

#ifndef HTTPCLIENT_MIN_DELAY_MS
#define HTTPCLIENT_MIN_DELAY_MS 1
#endif

#ifndef HTTPCLIENT_DEFAULT_ENFORCE_SAMESITE
#define HTTPCLIENT_DEFAULT_ENFORCE_SAMESITE 1
#endif

#ifndef HTTPCLIENT_MAX_COOKIES
#define HTTPCLIENT_MAX_COOKIES 10000
#endif

#ifndef HTTPCLIENT_COOKIE_HASH_SIZE
#define HTTPCLIENT_COOKIE_HASH_SIZE 127
#endif

#ifndef HTTPCLIENT_COOKIE_MAX_NAME_LEN
#define HTTPCLIENT_COOKIE_MAX_NAME_LEN 256
#endif

#ifndef HTTPCLIENT_COOKIE_MAX_VALUE_LEN
#define HTTPCLIENT_COOKIE_MAX_VALUE_LEN 4096
#endif

#ifndef HTTPCLIENT_COOKIE_MAX_DOMAIN_LEN
#define HTTPCLIENT_COOKIE_MAX_DOMAIN_LEN 256
#endif

#ifndef HTTPCLIENT_COOKIE_MAX_PATH_LEN
#define HTTPCLIENT_COOKIE_MAX_PATH_LEN 1024
#endif

#ifndef HTTPCLIENT_COOKIE_FILE_LINE_SIZE
#define HTTPCLIENT_COOKIE_FILE_LINE_SIZE 4096
#endif

#ifndef HTTPCLIENT_COOKIE_MAX_AGE_SIZE
#define HTTPCLIENT_COOKIE_MAX_AGE_SIZE 32
#endif

#ifndef HTTPCLIENT_COOKIE_SAMESITE_SIZE
#define HTTPCLIENT_COOKIE_SAMESITE_SIZE 16
#endif

#ifndef HTTPCLIENT_MAX_COOKIE_AGE_SEC
#define HTTPCLIENT_MAX_COOKIE_AGE_SEC (365LL * 24 * 3600 * 10)
#endif

#ifndef HTTPCLIENT_COOKIE_MAX_CHAIN_LEN
#define HTTPCLIENT_COOKIE_MAX_CHAIN_LEN 100
#endif

#ifndef HTTPCLIENT_DEFAULT_MAX_RESPONSE_SIZE
#define HTTPCLIENT_DEFAULT_MAX_RESPONSE_SIZE (10ULL * 1024 * 1024)
#endif

#ifndef HTTPCLIENT_AUTH_CREDENTIALS_SIZE
#define HTTPCLIENT_AUTH_CREDENTIALS_SIZE 512
#endif

#ifndef HTTPCLIENT_DIGEST_A_BUFFER_SIZE
#define HTTPCLIENT_DIGEST_A_BUFFER_SIZE 512
#endif

#ifndef HTTPCLIENT_DIGEST_RESPONSE_SIZE
#define HTTPCLIENT_DIGEST_RESPONSE_SIZE 256
#endif

#ifndef HTTPCLIENT_DIGEST_CNONCE_SIZE
#define HTTPCLIENT_DIGEST_CNONCE_SIZE 16
#endif

#ifndef HTTPCLIENT_DIGEST_CNONCE_HEX_SIZE
#define HTTPCLIENT_DIGEST_CNONCE_HEX_SIZE 33
#endif

#ifndef HTTPCLIENT_DIGEST_NC_SIZE
#define HTTPCLIENT_DIGEST_NC_SIZE 16
#endif

#ifndef HTTPCLIENT_REQUEST_BUFFER_SIZE
#define HTTPCLIENT_REQUEST_BUFFER_SIZE 8192
#endif

#ifndef HTTPCLIENT_BODY_CHUNK_SIZE
#define HTTPCLIENT_BODY_CHUNK_SIZE 4096
#endif

#ifndef HTTPCLIENT_H2_BODY_INITIAL_CAPACITY
#define HTTPCLIENT_H2_BODY_INITIAL_CAPACITY (64 * 1024)
#endif

#ifndef HTTPCLIENT_HOST_HEADER_SIZE
#define HTTPCLIENT_HOST_HEADER_SIZE 256
#endif

#ifndef HTTPCLIENT_COOKIE_HEADER_SIZE
#define HTTPCLIENT_COOKIE_HEADER_SIZE 4096
#endif

#ifndef HTTPCLIENT_AUTH_HEADER_SIZE
#define HTTPCLIENT_AUTH_HEADER_SIZE 512
#endif

#ifndef HTTPCLIENT_AUTH_HEADER_LARGE_SIZE
#define HTTPCLIENT_AUTH_HEADER_LARGE_SIZE 1024
#endif

#ifndef HTTPCLIENT_URI_BUFFER_SIZE
#define HTTPCLIENT_URI_BUFFER_SIZE 512
#endif

#ifndef HTTPCLIENT_MAX_SET_COOKIES
#define HTTPCLIENT_MAX_SET_COOKIES 16
#endif

#ifndef HTTPCLIENT_ACCEPT_ENCODING_SIZE
#define HTTPCLIENT_ACCEPT_ENCODING_SIZE 64
#endif

#ifndef HTTPCLIENT_CONTENT_LENGTH_SIZE
#define HTTPCLIENT_CONTENT_LENGTH_SIZE 32
#endif

#ifndef HTTPCLIENT_DEFAULT_USER_AGENT
#define HTTPCLIENT_DEFAULT_USER_AGENT "SocketHTTPClient/1.0"
#endif

/* Async I/O configuration (io_uring backend) */
#ifndef HTTPCLIENT_DEFAULT_ENABLE_ASYNC_IO
#define HTTPCLIENT_DEFAULT_ENABLE_ASYNC_IO 0
#endif

#ifndef HTTPCLIENT_ASYNC_IO_RING_SIZE
#define HTTPCLIENT_ASYNC_IO_RING_SIZE 64
#endif

#define HTTPCLIENT_ENCODING_IDENTITY 0x00
#define HTTPCLIENT_ENCODING_GZIP 0x01
#define HTTPCLIENT_ENCODING_DEFLATE 0x02
#define HTTPCLIENT_ENCODING_BR 0x04

#endif /* SOCKETHTTPCLIENT_CONFIG_INCLUDED */
